# Generated by Django 5.0.4 on 2024-04-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('specialization', models.CharField(choices=[('GP', 'General Practitioner'), ('IM', 'Internal Medicine'), ('ORTH', 'Orthopedic'), ('CARD', 'Cardiologist'), ('DENT', 'Dentist'), ('GYN', 'Gynecologist'), ('PUL', 'Pulmonologist')], max_length=50)),
                ('consultation_hours', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('insurance', models.CharField(max_length=50)),
                ('complaint', models.CharField(choices=[('headache', 'Headache'), ('backpain', 'Backpain'), ('kneepain', 'Kneepain'), ('fever', 'Fever'), ('cough', 'Cough'), ('throat ache', 'Throat ache'), ('sneezing', 'Sneezing'), ('body pain', 'Body pain'), ('tooth ache', 'Tooth ache')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_search.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_search.patient')),
            ],
        ),
    ]
