# Generated by Django 5.0.4 on 2024-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='floor_location',
            field=models.CharField(choices=[('F1', 'Floor 1'), ('F2', 'Floor 2'), ('F3', 'Floor 3'), ('F4', 'Floor 4')], default='Floor 1', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='room_location',
            field=models.CharField(choices=[('R1', 'Room 1'), ('R2', 'Room 2'), ('R3', 'Room 3'), ('R4', 'Room 4')], default='Room 1', max_length=50),
        ),
    ]
