# Generated by Django 5.0.4 on 2024-04-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.CharField(max_length=50),
        ),
    ]
