# Generated by Django 5.0.4 on 2024-04-28 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doc_search", "0002_alter_appointment_patient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="patient",
            new_name="patient_id",
        ),
    ]

