# Generated by Django 5.0.4 on 2024-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0003_businesshours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesshours',
            options={'ordering': ['id'], 'verbose_name': 'Business Hour', 'verbose_name_plural': 'Business Hours'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['specialization', 'first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_hours',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
