# Generated by Django 5.0.4 on 2024-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_search", "0003_rename_patient_appointment_patient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="complaint",
            field=models.CharField(
                choices=[
                    ("headache", "Headache"),
                    ("backpain", "Backpain"),
                    ("kneepain", "Kneepain"),
                    ("fever", "Fever"),
                    ("cough", "Cough"),
                    ("throat ache", "Throat ache"),
                    ("sneezing", "Sneezing"),
                    ("body pain", "Body pain"),
                    ("tooth ache", "Tooth ache"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
