# Generated by Django 5.0.4 on 2024-04-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0006_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['time']},
        ),
    ]
