# Generated by Django 4.2.11 on 2024-05-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doc_search", "0003_businesshours"),
        ("doc_search", "0006_timeslot"),
    ]

    operations = []

