# Generated by Django 5.0.4 on 2024-05-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_search', '0007_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date']},
        ),
    ]
