# Generated by Django 5.0.6 on 2024-05-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='number_of_doctors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='speciality',
            field=models.CharField(choices=[('Gastroenterology', 'Gastroenterology - Diagnosis and treatment of digestive system disorders.'), ('Hematology and Oncology', 'Hematology and Oncology - Diagnosis and treatment of blood diseases and cancer.'), ('Palliative Medicine and Internal Medicine', 'Palliative Medicine and Internal Medicine - Comprehensive care focusing on relief from symptoms and stress of serious illness.'), ('Vascular Surgery', 'Vascular Surgery - Treatment of circulatory disorders of arterial and venous vessels.'), ('Ear, Nose and Throat Medicine', 'Ear, Nose and Throat Medicine - Treatment of ENT disorders.'), ('Cardiology and Intensive Care Medicine', 'Cardiology and Intensive Care Medicine - Diagnosis and treatment of heart conditions and critical care.')], max_length=255),
        ),
    ]
