# Generated by Django 5.0.6 on 2024-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_hospital_number_of_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='number_of_beds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='number_of_nurses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='numbers_of_the_intensive_care_beds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
