# Generated by Django 5.0.6 on 2024-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_hospital_number_of_beds_hospital_number_of_nurses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='affiliated_specialist_practice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='aftercare_provider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='bus_stops_or_parking_spaces',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='canteens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='discharge_management',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_power',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='operating_rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='outpatient_clinics_focus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='wireless_Internet_access',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
