# Generated by Django 5.0.6 on 2024-05-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_hospital_affiliated_specialist_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='opening',
        ),
        migrations.AddField(
            model_name='hospital',
            name='visiting_hours_closing',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='visiting_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
